apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: st0d2r9d3-java-quarkus
  janus-idp.io/tekton: st0d2r9d3-java-quarkus
  backstage.io/kubernetes-id: st0d2r9d3-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: st0d2r9d3-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
